services:
  - type: web
    name: aganitha-task
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --skip-generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: file:./dev.db
    preDeployCommand: npx prisma migrate deploy --skip-generate || npx prisma db push --skip-generate
